In [23]:
!pip install pandas
!pip install tqdm

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in ./.local/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: pytz>=2020.1 in ./.local/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.local/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in ./.local/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: tzdata>=2022.7 in ./.local/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
Collecting tqdm
  Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 KB 1.7 MB/s eta 0:00:00a 0:00:01
Installing collected packages: tqdm
Successfully installed tqdm-4.67.1

In [24]:
import pandas as pd
import subprocess
from tqdm import tqdm

In [30]:
df = pd.read_csv('./output-bbox/iter_log.csv')
df.head(3)

,iter,src,mutator,seed,mutation_status,mutated_program,flags_count,flags,compilation_outcome,res_hash
0,1,/users/a_irmak/programs/test_1133.c,duplicate,1236057407,applied,/users/a_irmak/programs/test_1133_e28ac672.c,8,-fdenormal-fp-math=ieee -fno-fixed-point -mavx...,crash,e28ac6722de673e0cc44fa8b902f558c
1,2,/users/a_irmak/programs/test_581.c,jump,522404203,applied,/users/a_irmak/programs/test_581_8f64c6e3.c,3,-funsigned-bitfields -fno-align-functions -ffp...,crash,8f64c6e3b9414795ad0f0e0235350462
2,3,/users/a_irmak/programs/test_1201.c,delete,1999455680,failed,/users/a_irmak/programs/test_1201.c,2,-ffp-model=fast -ftls-model=local-exec,success,b0fd38665b7f47e052260f710084f537

In [31]:
crash_df = df[df['compilation_outcome'] == 'crash']
mutation_failed = df[df['mutation_status'] == 'failed'] # mutations give error generally cause of c standart version difference

In [33]:
outcome_counts = df['compilation_outcome'].value_counts()
mutation_failed_counts = df['mutation_status'].value_counts()
total_iterations = len(df)
print("Compilation Outcome Counts:")
print(outcome_counts)
print("\nMutation Status Counts:")
print(mutation_failed_counts)
print("\nTotal Iterations:")
print(total_iterations)

Compilation Outcome Counts:
compilation_outcome
success    544987
crash       70417
hang           15
Name: count, dtype: int64

Mutation Status Counts:
mutation_status
applied      401017
no-op        100027
skipped       61701
failed        45504
duplicate      7170
Name: count, dtype: int64

Total Iterations:
615419

In [34]:
# learn failed mutation reasons
failed_mut_reasons_mut = mutation_failed['mutator'].value_counts()
failed_mut_reasons_file = mutation_failed['src'].value_counts()

print("\nFailed Mutation Mutator Counts:")
print(failed_mut_reasons_mut)

print("\nFailed Mutation File Counts:")
print(failed_mut_reasons_file)

Failed Mutation Mutator Counts:
mutator
jump          9273
constant      9144
duplicate     9111
delete        9100
expression    8876
Name: count, dtype: int64

Failed Mutation File Counts:
src
/users/a_irmak/programs/test_860.c                                                                                               17
/users/a_irmak/programs/test_1001.c                                                                                              16
/users/a_irmak/programs/test_1011_0f6d780d_a11bd888_30820e8a.c                                                                   16
/users/a_irmak/programs/test_247.c                                                                                               16
/users/a_irmak/programs/test_101.c                                                                                               16
                                                                                                                                 ..
/users/a_irmak/programs/test_707_d3669fed_c5c1841f_acbcc5b2_88bacf64_121be6aa_9474b1c2_7d356a91.c                                 1
/users/a_irmak/programs/test_535_350691ae_9c22e0a2_82a15800_62ba5ea9_a8345ba7_14e52159.c                                          1
/users/a_irmak/programs/test_142_5d996d51_255355cf_ffd8033d_5f609886_8f92e4e6_2e2ea7fb.c                                          1
/users/a_irmak/programs/test_300_d599df46_ffedbc07_677b0636_f756b0e0_589427ef_009a6114.c                                          1
/users/a_irmak/programs/test_1764_e948481c_b0c42bd9_dd85d5ab_1307fb4a_827170da_5594536b_149758c3_9cb93e7d_e5673b2c_a89613a4.c     1
Name: count, Length: 17002, dtype: int64

In [16]:
mutation_failed

,iter,src,mutator,seed,mutation_status,mutated_program,flags_count,flags,compilation_outcome,res_hash
2,3,/users/a_irmak/programs/test_1201.c,delete,1999455680,failed,/users/a_irmak/programs/test_1201.c,2,-ffp-model=fast -ftls-model=local-exec,success,b0fd38665b7f47e052260f710084f537
4,5,/users/a_irmak/programs/test_470.c,jump,547024323,failed,/users/a_irmak/programs/test_470.c,9,-fmath-errno -fno-aligned-allocation -fapprox-...,success,6cea3705b6d4289915b1f2be7fb6a821
37,38,/users/a_irmak/programs/test_1412.c,duplicate,1541213181,failed,/users/a_irmak/programs/test_1412.c,2,-fvectorize -fno-fast-math,success,b521d370ff374b9952299e0e7bd49786
42,43,/users/a_irmak/programs/test_671.c,expression,1175565640,failed,/users/a_irmak/programs/test_671.c,1,-fstack-size-section,success,57ccb5ab2fed2297c1c36e8bb055caa3
47,48,/users/a_irmak/programs/test_1658.c,duplicate,1990340714,failed,/users/a_irmak/programs/test_1658.c,3,-fno-stack-size-section -fno-signed-zeros -fho...,success,fdbcf739d2ae9c98155c3d74d8c2ada8
...,...,...,...,...,...,...,...,...,...,...
594014,594015,/users/a_irmak/programs/test_1362_9ddea711_ed9...,delete,2058474375,failed,/users/a_irmak/programs/test_1362_9ddea711_ed9...,5,-fno-align-functions -fprotect-parens -funsafe...,crash,d1e58dc01bac1a88cabaaed78c9e7d29
594050,594051,/users/a_irmak/programs/test_1133_d704ede3_af4...,jump,1108753699,failed,/users/a_irmak/programs/test_1133_d704ede3_af4...,5,-fkeep-persistent-storage-variables -fhonor-na...,crash,78089dfa72f1ef2510865f92f6605018
594064,594065,/users/a_irmak/programs/test_1609_e21a3547_3d9...,delete,1277790184,failed,/users/a_irmak/programs/test_1609_e21a3547_3d9...,7,-O2 -fsigned-char -fno-use-init-array -fno-fas...,crash,719d616600d6469499acb34326eef152
594099,594100,/users/a_irmak/programs/test_524_52d6ee75_35ca...,delete,444017519,failed,/users/a_irmak/programs/test_524_52d6ee75_35ca...,6,-fno-signed-char -fsigned-bitfields -ffp-excep...,crash,f36325a745f62e057562b928f8710a96
594109,594110,/users/a_irmak/programs/test_535_350691ae_9c22...,delete,90861464,failed,/users/a_irmak/programs/test_535_350691ae_9c22...,1,-ffp-model=fast,crash,4fd02b5f76a2355d36b23223995cd218

In [35]:
crash_df

,iter,src,mutator,seed,mutation_status,mutated_program,flags_count,flags,compilation_outcome,res_hash
0,1,/users/a_irmak/programs/test_1133.c,duplicate,1236057407,applied,/users/a_irmak/programs/test_1133_e28ac672.c,8,-fdenormal-fp-math=ieee -fno-fixed-point -mavx...,crash,e28ac6722de673e0cc44fa8b902f558c
1,2,/users/a_irmak/programs/test_581.c,jump,522404203,applied,/users/a_irmak/programs/test_581_8f64c6e3.c,3,-funsigned-bitfields -fno-align-functions -ffp...,crash,8f64c6e3b9414795ad0f0e0235350462
5,6,/users/a_irmak/programs/test_1179.c,expression,2035156725,applied,/users/a_irmak/programs/test_1179_473b6997.c,10,-msha -fhonor-infinities -fno-unwind-tables -m...,crash,473b69976f8caec3a0b0de2293c0079c
21,22,/users/a_irmak/programs/test_948.c,duplicate,379796964,applied,/users/a_irmak/programs/test_948_fc52253c.c,8,-fdenormal-fp-math=preserve-sign -fassociative...,crash,fc52253c854efcdb9949a4855fcbdd9a
25,26,/users/a_irmak/programs/test_88.c,duplicate,1968690737,applied,/users/a_irmak/programs/test_88_92645b69.c,3,-fno-unsigned-char -faddrsig -fvectorize,crash,92645b6953da1e81eaa619e98870fec9
...,...,...,...,...,...,...,...,...,...,...
615376,615377,/users/a_irmak/programs/test_923_32d1e2c7_bd69...,duplicate,1596068809,applied,/users/a_irmak/programs/test_923_32d1e2c7_bd69...,3,-Og -mavx2 -fno-associative-math,crash,a91f1a53d652ae2ccee6f286f7086b61
615377,615378,/users/a_irmak/programs/test_1011_137d723d_610...,jump,1518532476,applied,/users/a_irmak/programs/test_1011_137d723d_610...,2,-fno-approx-func -funsigned-bitfields,crash,ef4f97e1484f3757fee183d3c25503b3
615382,615383,/users/a_irmak/programs/test_34_69a15396_265e7...,duplicate,1989181808,applied,/users/a_irmak/programs/test_34_69a15396_265e7...,4,-ffp-eval-method=double -falign-functions -fno...,crash,ea4d512f968d41a851be97afb3b147c5
615394,615395,/users/a_irmak/programs/test_534_f3cd3fb2_5ca7...,jump,1037619925,failed,/users/a_irmak/programs/test_534_f3cd3fb2_5ca7...,5,-fdenormal-fp-math=ieee -fstack-size-section -...,crash,2943c9f804d559a2428b056279abce3b
615400,615401,/users/a_irmak/programs/test_1609_e21a3547_3d9...,-,-,skipped,/users/a_irmak/programs/test_1609_e21a3547_3d9...,4,-funsigned-char -fno-lax-vector-conversions -f...,crash,42c8acc7974444992cb7072771179cf4

In [36]:
def compile_and_get_return_code(mutated_program, flags):
    """Compile a mutated program and return the exit code"""
    cmd = [
        '/opt/llvm-latest/bin/clang',
        mutated_program,
        '-c',
        '-fpermissive',
        '-w',
        '-Wno-implicit-function-declaration',
        '-Wno-return-type',
        '-Wno-builtin-redeclared',
        '-Wno-implicit-int',
        '-Wno-int-conversion',
        '-march=native',
        '-I/usr/include',
        '-I/users/a_irmak/llvmSS-include'
    ]
    
    # Add extra flags if they exist
    if pd.notna(flags) and flags:
        cmd.extend(flags.split())
    
    try:
        result = subprocess.run(cmd, capture_output=True, timeout=60)
        return result.returncode
    except subprocess.TimeoutExpired:
        return -1  # Timeout
    except Exception as e:
        return -2  # Other error

# Apply the compilation function to each row with progress bar
tqdm.pandas()
crash_df['return_code'] = crash_df.progress_apply(
    lambda row: compile_and_get_return_code(row['mutated_program'], row['flags']),
    axis=1
)

print(crash_df[['mutated_program', 'flags', 'return_code']].head(10))
print("\nReturn Code Distribution:")
print(crash_df['return_code'].value_counts().sort_index())

  0%|          | 4/70417 [00:00<30:19, 38.69it/s]

100%|██████████| 70417/70417 [39:13<00:00, 29.92it/s]

                                 mutated_program  \
0   /users/a_irmak/programs/test_1133_e28ac672.c
1    /users/a_irmak/programs/test_581_8f64c6e3.c
5   /users/a_irmak/programs/test_1179_473b6997.c
21   /users/a_irmak/programs/test_948_fc52253c.c
25    /users/a_irmak/programs/test_88_92645b69.c
26  /users/a_irmak/programs/test_1773_55056f47.c
67   /users/a_irmak/programs/test_588_7cf11b54.c
71    /users/a_irmak/programs/test_56_cc407608.c
74  /users/a_irmak/programs/test_1073_5495477d.c
75   /users/a_irmak/programs/test_554_31f70579.c

                                                flags  return_code
0   -fdenormal-fp-math=ieee -fno-fixed-point -mavx...            1
1   -funsigned-bitfields -fno-align-functions -ffp...            1
5   -msha -fhonor-infinities -fno-unwind-tables -m...            1
21  -fdenormal-fp-math=preserve-sign -fassociative...            1
25           -fno-unsigned-char -faddrsig -fvectorize            1
26                               -fno-strict-overflow            1
67  -fno-function-sections -ffinite-math-only -fno...            1
71         -fstack-protector-strong -ffp-contract=off            1
74  -fno-stack-protector -ftls-model=local-dynamic...            1
75  -ffinite-loops -fno-unwind-tables -ffp-contrac...            1

Return Code Distribution:
return_code
-11        2
 0       102
 1     70313
Name: count, dtype: int64

/tmp/ipykernel_1319418/2117847419.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crash_df['return_code'] = crash_df.progress_apply(

In [37]:
crash_df

,iter,src,mutator,seed,mutation_status,mutated_program,flags_count,flags,compilation_outcome,res_hash,return_code
0,1,/users/a_irmak/programs/test_1133.c,duplicate,1236057407,applied,/users/a_irmak/programs/test_1133_e28ac672.c,8,-fdenormal-fp-math=ieee -fno-fixed-point -mavx...,crash,e28ac6722de673e0cc44fa8b902f558c,1
1,2,/users/a_irmak/programs/test_581.c,jump,522404203,applied,/users/a_irmak/programs/test_581_8f64c6e3.c,3,-funsigned-bitfields -fno-align-functions -ffp...,crash,8f64c6e3b9414795ad0f0e0235350462,1
5,6,/users/a_irmak/programs/test_1179.c,expression,2035156725,applied,/users/a_irmak/programs/test_1179_473b6997.c,10,-msha -fhonor-infinities -fno-unwind-tables -m...,crash,473b69976f8caec3a0b0de2293c0079c,1
21,22,/users/a_irmak/programs/test_948.c,duplicate,379796964,applied,/users/a_irmak/programs/test_948_fc52253c.c,8,-fdenormal-fp-math=preserve-sign -fassociative...,crash,fc52253c854efcdb9949a4855fcbdd9a,1
25,26,/users/a_irmak/programs/test_88.c,duplicate,1968690737,applied,/users/a_irmak/programs/test_88_92645b69.c,3,-fno-unsigned-char -faddrsig -fvectorize,crash,92645b6953da1e81eaa619e98870fec9,1
...,...,...,...,...,...,...,...,...,...,...,...
615376,615377,/users/a_irmak/programs/test_923_32d1e2c7_bd69...,duplicate,1596068809,applied,/users/a_irmak/programs/test_923_32d1e2c7_bd69...,3,-Og -mavx2 -fno-associative-math,crash,a91f1a53d652ae2ccee6f286f7086b61,1
615377,615378,/users/a_irmak/programs/test_1011_137d723d_610...,jump,1518532476,applied,/users/a_irmak/programs/test_1011_137d723d_610...,2,-fno-approx-func -funsigned-bitfields,crash,ef4f97e1484f3757fee183d3c25503b3,1
615382,615383,/users/a_irmak/programs/test_34_69a15396_265e7...,duplicate,1989181808,applied,/users/a_irmak/programs/test_34_69a15396_265e7...,4,-ffp-eval-method=double -falign-functions -fno...,crash,ea4d512f968d41a851be97afb3b147c5,1
615394,615395,/users/a_irmak/programs/test_534_f3cd3fb2_5ca7...,jump,1037619925,failed,/users/a_irmak/programs/test_534_f3cd3fb2_5ca7...,5,-fdenormal-fp-math=ieee -fstack-size-section -...,crash,2943c9f804d559a2428b056279abce3b,1
615400,615401,/users/a_irmak/programs/test_1609_e21a3547_3d9...,-,-,skipped,/users/a_irmak/programs/test_1609_e21a3547_3d9...,4,-funsigned-char -fno-lax-vector-conversions -f...,crash,42c8acc7974444992cb7072771179cf4,1

In [38]:
crash_df['return_code'].value_counts().sort_index()

return_code
-11        2
 0       102
 1     70313
Name: count, dtype: int64

In [41]:
segfault_df = crash_df[crash_df['return_code'] == -11]
for program in segfault_df['mutated_program'].tolist():
    print(f"Segfault in program: {program}")
    print(segfault_df[segfault_df['mutated_program'] == program][['flags']].values.tolist())

Segfault in program: /users/a_irmak/programs/test_1609_e21a3547_3d9d921b_068b9d94_6d4734f3_4dd78440_b28bb6f7_221c4b02_d710a80e_8a962bd7_0a416e5d_6229703d.c
[['-O3 -fno-honor-infinities -fno-strict-overflow -march=x86-64-v3 -freciprocal-math -fno-vectorize -fno-keep-persistent-storage-variables -fdenormal-fp-math=ieee -fstrict-overflow']]
Segfault in program: /users/a_irmak/programs/test_1609_e21a3547_3d9d921b_a108ad26_1945d758_1b895280_e6d92a89.c
[['-Ofast -fno-unsafe-math-optimizations -ftls-model=global-dynamic -march=x86-64-v3 -ffinite-math-only -fno-keep-static-consts -fno-finite-loops -fsigned-char -fno-aligned-allocation -fexcess-precision=fast']]